BR:git thus fixing build
+ /usr/bin/git init -q
/var/tmp/rpm-tmp.TpRXzP: line 40: /usr/bin/git: No such file or
directory
error: Bad exit status from /var/tmp/rpm-tmp.TpRXzP (%prep)

Change-Id: Icb08a0615c611a76bedf4e57ed45531d5f131114